[keybinds]
# Personal
"Mod+E" = "spawn:kitty -e yazi"
"Mod+Return" = "spawn:kitty"
"Mod+B" = "spawn:firefox"
"Mod+G" = "spawn:flatpak run com.google.Chrome"
"Mod+O" = "spawn:obs"
"Mod+N" = "spawn:flatpak run org.gnome.TextEditor"
"Mod+P" = "spawn:foot --class PrintTerminal -- /home/weng/.local/bin/print_pdf.sh"

# Noctalia
"Mod+Space" = "spawn:noctalia msg panel-toggle launcher"
"Mod+V" = "spawn:noctalia msg panel-toggle clipboard"
"Mod+W" = "spawn:noctalia msg panel-toggle wallpaper"
# "Mod+X" = "spawn:noctalia msg bar-toggle" # 隐藏bar
"Mod+X" = "spawn:noctalia msg panel-toggle session"
"Mod+S" = "spawn:noctalia msg settings-toggle"
"Mod+Print" = "spawn:noctalia msg screenshot-region"
"Mod+Shift+Print" = "spawn:noctalia msg screenshot-fullscreen"
"Mod+Alt+Print" = "spawn:noctalia msg screenshot-fullscreen pick" # 全屏截图(多屏选择)
# 截图另一种实现
# 总开关：按下 Mod+Print 进入截图模式
# "Mod+Print" = { action = "submap:screenshot", repeat = false }
# 按数字键 1：区域截图
# "submap[screenshot],1" = { action = "spawn:sh -c 'grim -g \"$(slurp)\" ~/Pictures/Screenshot_$(date +%Y%m%d_%H%M%S).png'", submap = "reset" }
# 按数字键 2：全屏截图
# "submap[screenshot],2" = { action = "spawn:sh -c 'grim ~/Pictures/Screenshot_$(date +%Y%m%d_%H%M%S).png'", submap = "reset" }
# 按3：全屏截图，但多屏选择
# "submap[screenshot],3" = { action = "spawn:sh -c 'grim -o \"$(slurp -p -f %o)\" ~/Pictures/Screenshot_$(date +%Y%m%d_%H%M%S).png'", submap = "reset" }
# 按 Escape 键安全退出模式
# "submap[screenshot],Escape" = "submap:reset"

# Setting
"XF86MonBrightnessDown" = { action = "spawn:noctalia msg brightness-down 10", allow_when_locked = true }
"XF86MonBrightnessUp" = { action = "spawn:noctalia msg brightness-up 10", allow_when_locked = true }
"XF86AudioRaiseVolume" = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
"XF86AudioLowerVolume" = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
"XF86AudioMute" = "spawn:wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
"XF86AudioPlay" = "spawn:playerctl play-pause"
"XF86AudioNext" = "spawn:playerctl next"
"XF86AudioPrev" = "spawn:playerctl previous"
"XF86KbdBrightnessUp"   = "spawn:brightnessctl -d smc::kbd_backlight set +10%"
"XF86KbdBrightnessDown" = "spawn:brightnessctl -d smc::kbd_backlight set 10%-"
"XF86LaunchA" = { action = "overview-toggle", repeat = false } # mac键盘的F3
"XF86LaunchB" = "spawn:noctalia msg screenshot-region" # mac键盘的F4
"Mod+XF86LaunchB" = { action = "spawn:noctalia msg screenshot-fullscreen", repeat = false }

# Window 
"Mod+C" = "column-center"
"Mod+R" = "window-cycle-width"
"Mod+T" = "window-toggle-floating"
"Mod+Shift+T" = "window-toggle-pinned"
"Mod+F" = "window-toggle-maximize"
# "Mod+Shift+F" = "window-toggle-maximize-to-edges" # 展开至边界
"Mod+Shift+F" = "window-toggle-fullscreen" # 全屏
"Mod+Up" = "window-focus-or-workspace-up"
"Mod+Down" = "window-focus-or-workspace-down"
"Mod+Left" = "window-focus-or-output-left"
"Mod+Right" = "window-focus-or-output-right"
"Mod+Ctrl+Up" = "window-move-or-workspace-up"
"Mod+Ctrl+Down" = "window-move-or-workspace-down"
"Mod+Ctrl+Left" = "window-move-or-output-left"
"Mod+Ctrl+Right" = "window-move-or-output-right"
"Mod+Q" = {action = "window-close", repeat = false}
"Mod+Tab" = {action = "overview-toggle", repeat = false}

# Workspace switching
"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"

# Move window to workspace
"Mod+Ctrl+1" = "window-move-to-workspace:1"
"Mod+Ctrl+2" = "window-move-to-workspace:2"
"Mod+Ctrl+3" = "window-move-to-workspace:3"
"Mod+Ctrl+4" = "window-move-to-workspace:4"
"Mod+Ctrl+5" = "window-move-to-workspace:5"
"Mod+Ctrl+6" = "window-move-to-workspace:6"
"Mod+Ctrl+7" = "window-move-to-workspace:7"
"Mod+Ctrl+8" = "window-move-to-workspace:8"
"Mod+Ctrl+9" = "window-move-to-workspace:9"

"Mod+WheelUp" = "window-focus-left"
"Mod+WheelDown" = "window-focus-right"
"Mod+Shift+WheelUp" = "column-move-left"
"Mod+Shift+WheelDown" = "column-move-right"
"Mod+MouseMiddle" = "overview-toggle"
