[colors]
background = "#45403dFF"
text_primary = "#ebdbb2FF"
text_muted = "#ebdbb2FF"
accent_primary = "#b8bb26FF"
accent_secondary = "#83a598FF"
warning = "#fe8019FF"
error = "#fb4934FF"
insert_hint = "#fe801980"
backdrop = "#45403dFF"

[colors.border]
focused = "#b8bb26FF"
unfocused = "#45403dFF"
scratchpad_focused = "#fe8019FF"
scratchpad_unfocused = "#642d00FF"
outer = "#282828FF"

[colors.overview]
background_tint = "#28282888"
badge = "#b8bb26FF"
workspace_background = "#282828FF"
