[accessibility]
ui_scale = 1.5000000149011612

[backdrop]
enabled = true

[bar.default]
center = [ "clock", "control-center", "date" ]
end = [ "tray", "notifications", "clipboard", "network", "widget" ]
margin_ends = 0
radius = 0
scale = 1.2500000111758709
start = [ "workspaces", "cat" ]
widget_spacing = 12

[desktop_widgets]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugin_settings."blackbartblues/audio-switcher"]
audio-switcher_placement = "floating"

[plugins]
enabled = [ "dotnetrob/cat", "icefish/phone-connect", "blackbartblues/audio-switcher" ]

[shell]
external_ip_enabled = true
font_family = "LXGW Bright GB"
lang = "zh-Hans"

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kitty", "niri", "qt", "starship" ]
    community_ids = [ "opencode", "steam", "fuzzel", "obs", "bat", "yazi" ]

[wallpaper.default]
path = "/home/weng/Pictures/wallpapers/wallpaper-96yottea.jpg"

[wallpaper.last]
path = "/home/weng/Pictures/wallpapers/wallpaper-96yottea.jpg"

[wallpaper.monitors.DP-2]
path = "/home/weng/Pictures/wallpapers/wallpaper-96yottea.jpg"

[[wallpaper.favorite]]
builtin_palette = "Tokyo-Night"
palette_source = "builtin"
path = "/home/weng/Pictures/wallpapers/wallpaper-96yottea.jpg"
theme_mode = "dark"

[widget.cat]
cat_color_mode = "custom"
interactive = false
type = "dotnetrob/cat:cat"

[widget.control-center]
anchor = true
glyph = "brand-redhat"

[widget.theme_mode]
enabled = false

[widget.volume]
enabled = false

[widget.widget]
type = "blackbartblues/audio-switcher:widget"
