# vim: ft=dosini
[Metadata]
Name=Gruvbox Light
Version=1.0
Author=khoocw97
Description=Gruvbox Material Light Hard
ScaleWithDPI=True

[InputPanel]
Spacing=3

# Unselected candidate color
# fg
NormalColor=#654735
# Selected candidate color
# bg0, light text on accent box (4.95:1)
HighlightCandidateColor=#f9f5d7
# Input character color
# Blue
HighlightColor=#45707a
# Input character background color
# bg0
HighlightBackgroundColor=#f9f5d7

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background]
# bg0
Color=#f9f5d7

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
# Blue
Color=#45707a

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8

[Menu]
# fg
NormalColor=#654735
Spacing=3

[Menu/Background]
# bg0
Color=#f9f5d7

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
# Blue
Color=#45707a

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
# Grey
Color=#928374

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
