# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#4c7a5d" }

# Find
find_keyword  = { fg = "#b47109", bold = true, italic = true, underline = true }
find_position = { fg = "#945e80", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#6c782e", bg = "#6c782e" }
marker_cut      = { fg = "#c14a4a", bg = "#c14a4a" }
marker_marked   = { fg = "#4c7a5d", bg = "#4c7a5d" }
marker_selected = { fg = "#928374", bg = "#928374" }

# Count
count_copied   = { fg = "#f9f5d7", bg = "#6c782e" }
count_cut      = { fg = "#f9f5d7", bg = "#c14a4a" }
count_selected = { fg = "#f9f5d7", bg = "#b47109" }

# Border
border_symbol = "│"
border_style  = { fg = "#928374" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#f9f5d7", bg = "#45707a", bold = true }
inactive = { fg = "#45707a", bg = "#f3eac7" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#f9f5d7", bg = "#45707a", bold = true }
normal_alt  = { fg = "#45707a", bg = "#f3eac7" }

# Select mode
select_main = { fg = "#f9f5d7", bg = "#4c7a5d", bold = true }
select_alt  = { fg = "#4c7a5d", bg = "#f3eac7" }

# Unset mode
unset_main = { fg = "#f9f5d7", bg = "#c35e0a", bold = true }
unset_alt  = { fg = "#c35e0a", bg = "#f3eac7" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#928374" }
perm_type  = { fg = "#45707a" }
perm_read  = { fg = "#b47109" }
perm_write = { fg = "#c14a4a" }
perm_exec  = { fg = "#6c782e" }

# Progress
progress_label  = { fg = "#4f3829", bold = true }
progress_normal = { fg = "#6c782e", bg = "#f3eac7" }
progress_error  = { fg = "#b47109", bg = "#c14a4a" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#45707a" }
active   = { fg = "#945e80", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#45707a" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#45707a" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#45707a" }
title   = {}
hovered = { fg = "#945e80", bold = true }

# : }}}


# : Which {{{

[which]
border          = { fg = "#45707a" }
cand            = { fg = "#4c7a5d" }
rest            = { fg = "#928374" }
desc            = { fg = "#945e80" }
separator       = "  "
separator_style = { fg = "#928374" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#4c7a5d" }
run     = { fg = "#945e80" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#f3eac7", bg = "#4f3829" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#45707a" }
title    = { fg = "#45707a" }
tbl_col  = { fg = "#4c7a5d" }
tbl_cell = { fg = "#945e80", bg = "#f3eac7" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#6c782e" }
title_warn  = { fg = "#b47109" }
title_error = { fg = "#c14a4a" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "**/image/*", fg = "#4c7a5d" },
	# Media
	{ mime = "**/{audio,video}/*", fg = "#b47109" },
	# Archive
	{ mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#945e80" },
	# Document
	{ mime = "**/application/{pdf,doc,rtf}", fg = "#6c782e" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#928374" },
	# Fallback
	{ url = "*", fg = "#4f3829" },
	{ url = "*/", fg = "#45707a" },
]

# : }}}

[icon]

dirs = [
	{ name = ".config", text = "", fg = "#945e80" },
	{ name = ".git", text = "", fg = "#4c7a5d" },
	{ name = ".github", text = "", fg = "#45707a" },
	{ name = ".npm", text = "", fg = "#45707a" },
	{ name = "Desktop", text = "", fg = "#4c7a5d" },
	{ name = "Development", text = "", fg = "#4c7a5d" },
	{ name = "Documents", text = "", fg = "#4c7a5d" },
	{ name = "Downloads", text = "", fg = "#4c7a5d" },
	{ name = "Library", text = "", fg = "#4c7a5d" },
	{ name = "Movies", text = "", fg = "#4c7a5d" },
	{ name = "Music", text = "", fg = "#4c7a5d" },
	{ name = "Pictures", text = "", fg = "#4c7a5d" },
	{ name = "Public", text = "", fg = "#4c7a5d" },
	{ name = "Videos", text = "", fg = "#4c7a5d" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#4f3829" },
	{ if = "link", text = "", fg = "#928374" },
	{ if = "block", text = "", fg = "#c14a4a" },
	{ if = "char", text = "", fg = "#c14a4a" },
	{ if = "fifo", text = "", fg = "#c14a4a" },
	{ if = "sock", text = "", fg = "#c14a4a" },
	{ if = "sticky", text = "", fg = "#c14a4a" },
	{ if = "dummy", text = "", fg = "#c14a4a" },

	# Fallback
	{ if = "dir & hovered", text = "", fg = "#45707a" },
	{ if = "dir", text = "", fg = "#45707a" },
	{ if = "exec", text = "", fg = "#6c782e" },
	{ if = "!dir", text = "", fg = "#4f3829" },
]
