# vim: ft=dosini
[Metadata]
Name=Tokyo Night
Version=1.0
Author=khoocw97
Description=Tokyo Night for Fcitx5

[InputPanel]
Spacing=3

# Unselected candidate color
# Text
NormalColor=#c0caf5
# Selected candidate color
# bg0, dark text on accent box
HighlightCandidateColor=#1a1b26
# Input character color
# Blue
HighlightColor=#7aa2f7
# Input character background color
# bg0
HighlightBackgroundColor=#1a1b26

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background]
# bg0
Color=#1a1b26

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
# Blue
Color=#7aa2f7

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8

[Menu]
# Text
NormalColor=#c0caf5
Spacing=3

[Menu/Background]
# bg0
Color=#1a1b26

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
# Blue
Color=#7aa2f7

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
# Comment grey
Color=#565f89

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
